name: Build Zigbee2MQTT (OpenWrt)

on:
  workflow_dispatch:
  push:

env:
  OPENWRT_VERSION: "24.10.5"
  TARGET: "mediatek"
  SUBTARGET: "filogic"
  
jobs:
  build:
    runs-on: ubuntu-22.04

    steps:
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install -y build-essential clang flex bison g++ gawk \
          gcc-multilib g++-multilib gettext git libncurses-dev libssl-dev \
          python3-distutils rsync unzip zlib1g-dev file wget curl

      - name: Download OpenWrt SDK
        run: |
          wget https://downloads.openwrt.org/releases/${OPENWRT_VERSION}/targets/${TARGET}/${SUBTARGET}/openwrt-sdk-${OPENWRT_VERSION}-${TARGET}-${SUBTARGET}_gcc-13.3.0_musl.Linux-x86_64.tar.zst
          tar --zstd -xf openwrt-sdk-*.tar.zst
          mkdir -p sdk
          mv openwrt-sdk-*/* sdk/
          rm openwrt-sdk-*.tar.zst
          rmdir openwrt-sdk-*

      - name: Restore cache (dl + toolchain)
        uses: actions/cache@v4
        with:
          path: |
            sdk/dl
            sdk/staging_dir
            sdk/build_dir
          key: openwrt-${{ env.OPENWRT_VERSION }}-${{ env.TARGET }}-${{ env.SUBTARGET }}-${{ hashFiles('**/Makefile') }}
          restore-keys: |
            openwrt-${{ env.OPENWRT_VERSION }}-${{ env.TARGET }}-${{ env.SUBTARGET }}-
        
      - name: Add custom feed
        run: |
          cd sdk
          echo "src-git node https://github.com/nxhack/openwrt-node-packages.git" >> feeds.conf.default

      - name: Update & install feeds
        run: |
          cd sdk
          ./scripts/feeds update -a
          ./scripts/feeds install -a

      - name: Configure
        run: |
          cd sdk
          make defconfig

      - name: Build package
        run: |
          cd sdk
          make package/feeds/node/compile V=s -j$(nproc)

      - name: Upload IPK
        uses: actions/upload-artifact@v4
        with:
          name: node-ipk
          path: sdk/bin/packages/**/node*.ipk

       - name: Prepare repo
        run: |
          mkdir -p repo
          find sdk/bin/packages -name "*.ipk" -exec cp {} repo/ \;

      - name: Generate Packages index
        run: |
          cd sdk
          ./staging_dir/host/bin/opkg-make-index ../repo > ../repo/Packages
          gzip -k -f ../repo/Packages

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./repo
